# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: shellcheck --external-sources script/*

  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.7.2-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: script/bootstrap

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: typecheck
          command: script/typecheck

      - run:
          name: run tests
          command: script/test
      
      - run:
          name: check formatting
          when: always
          command: script/reformat --diff
      
      - run:
          name: try installing
          command: script/test_install --skip-license

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build:
          requires:
            - shellcheck
