# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

defaults: &defaults
  docker:
    # https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/python:3.7.2-stretch

  working_directory: ~/repo

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: shellcheck --external-sources script/*

  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            # when requirements change, use increasingly general patterns to restore cache
            - test-v1-dependencies-{{ checksum "requirements.txt" }}
            - test-v1-dependencies-

      - run:
          name: install dependencies
          command: script/bootstrap

      - save_cache:
          paths:
            - ./venv
          key: test-v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: typecheck
          command: script/typecheck

      - run:
          name: run tests
          command: script/test
      
      - run:
          name: check formatting
          when: always
          command: script/reformat --diff

  test installing:
    <<: *defaults

    steps:
      - checkout
      
      - run:
          command: script/test_install

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - test:
          requires:
            - shellcheck
      - test installing
